apiVersion: v1
kind: Pod
metadata:
  name: annotation-second-scheduler
  labels:
    name: multischeduler-example
spec:
  schedulerName: scheduler-plugins-scheduler
  containers:
  - name: pod-with-second-annotation-container
    image: localhost:5002/appedge
    # ports:
    # - containerPort: 8080
