apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: multischeduler-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007