
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - scheduling.sigs.k8s.io
  resources:
  - elasticquota
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.k8s5g.com
  resources:
  - networkinfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.sigs.k8s.io
  resources:
  - elasticquota/finalizers
  verbs:
  - update
- apiGroups:
  - scheduling.sigs.k8s.io
  resources:
  - elasticquota/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scheduling.sigs.k8s.io
  resources:
  - podgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.sigs.k8s.io
  resources:
  - podgroups/finalizers
  verbs:
  - update
- apiGroups:
  - scheduling.sigs.k8s.io
  resources:
  - podgroups/status
  verbs:
  - get
  - patch
  - update
